baseURL = ""
languageCode = "en"
title = ""
disableKinds = ["taxonomy"]
[params]
  tagline = ""
  description = ""
  images = ['/images/opengraph.png']
  phone = ""
  whatsapp = ""
  email = ""
  instagram = ""
  facebook = ""
  youtube = ""
  googleanalytics = ""

#[markup.goldmark.renderer]
 # unsafe = true # Allow HTML in md files
